import type { Metadata } from "next";
import localfont from 'next/font/local';
import { Inter } from "next/font/google";
import Navber from "@/components/Navber";
import Footer from '@/components/Footer';
import { CartProvider } from '@/context/Index'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const futura = localfont({
  src: [
    {
      path: '../../public/fonts/Futura-Bold.ttf',
      weight: '100'
    }
  ],
  variable: "--font-futura"
});

const helveticaNowText = localfont({
  src: [
    {
      path: '../../public/fonts/HelveticaNowText-Regular.ttf',
      weight: 'normal'
    }
  ],
  variable: "--font-helvetica-now-text"
});


export const metadata: Metadata = {
  title: "Good Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${futura.variable}`}>
        <CartProvider>
          <Navber />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
